---
- hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

   - name: install the mysql packages
     apt: name={{ item }} state=installed update_cache=yes
     with_items:
       - mysql-server
       - mysql-client
       - python-mysqldb

   - name: create database user
     mysql_user: user={{mysql_user}} password={{mysql_pass}} host={{mysql_user_host}} priv=*.*:ALL state=present

   - name: create trade_log database
     mysql_db: db=trade_log state=present

   - name: create trade_history database
     mysql_db: db=trade_history state=present

   - name: set bind address
     lineinfile:
         dest: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '^bind-address            = 127.0.0.1'
         line: 'bind-address            = 0.0.0.0'

   - name: restart mysql
     service: name=mysql state=restarted
