---
- hosts: all
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

    - include: build_viaxch.yml

    - name: create log directory
      file: path=/var/log/trade/ state=directory

    # using named groups due to ansible munging backrefs next to numbers (http://www.handverdrahtet.org/2016/01/ansible-using-numbered-backreference.html)
    - name:
      shell: perl -i -p0e 's/{{ item.regexp }}/{{ item.replace }}/s' {{root_dir}}/marketprice/config.json
      with_items:
          - { regexp: '(?<one>"deals": \{[^\{]*"brokers": ")(127.0.0.1)(?<three>:9092",)',
              replace: '$+{one}{{kafka_host}}$+{three}' }
          - { regexp: '(?<one>"redis": \{[^\{]*"addr": \[[^\{]*")(127.0.0.1)(?<three>:26381",)',
              replace: '$+{one}{{redis_host}}$+{three}' }
          - { regexp: '(?<one>"redis": \{[^\{]*"addr": \[[^\{]*")(127.0.0.1)(?<three>:26382",)',
              replace: '$+{one}{{redis_host}}$+{three}' }
          - { regexp: '(?<one>"redis": \{[^\{]*"addr": \[[^\{]*")(127.0.0.1)(?<three>:26383")',
              replace: '$+{one}{{redis_host}}$+{three}' }

    - name: restart server
      shell: '{{root_dir}}/marketprice/marketprice.exe {{root_dir}}/marketprice/config.json'
