---
- hosts: all
  vars:
    redis_port: 6379
  become: true
  gather_facts: False
  pre_tasks:
    # Ansible requires python2, which is not installed by default on Ubuntu Xenial
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    # action: setup will gather facts after python2 has been installed
    - action: setup
  tasks:

   - name: install the redis packages
     apt: name={{ item }} state=installed update_cache=yes
     with_items:
       - redis-server
       - redis-tools

   - name: add redis.local.conf template
     template: src=templates/redis.local.conf.j2 dest=/etc/redis/redis.local.conf group=redis owner=redis

   - name: add redis.local.conf include to redis.conf
     lineinfile:
       dest: /etc/redis/redis.conf
       line: 'include /etc/redis/redis.local.conf'

   - name: restart redis
     service: name=redis state=restarted
